name: 'Terraform Dev/Test CD'

on:
  workflow_dispatch:
    inputs:
      destroy_enabled:
        type: boolean
        description: 'Destroy Resources?'
        default: false
      envtype:
        type: choice
        description: 'Execution Environment Type:'
        required: true
        options:
        - Dev
        - Test
      aws_account_name:
        type: string
        description: 'AWS Account Name:'
        required: true
      aws_account_id:
        type: string
        description: 'AWS Account Id:'
        required: true
      application:
        type: string
        description: 'Provide a comma separated list of applications (surround list with []):'
        default: '[B2B,ECU,CSL,ECU,PAYS,PMAN,WEB,SQLPROD,SQLMAST]'
        required: true
      ext_lb_enabled:
        type: choice
        description: External Load balancer Required?
        options:
        - "false"
        - "true"
        required: true
      project:
        type: string
        description: Project environment build for?
        default: 'Performance Team'
        required: true
      costowner:
        type: string
        description: 'Environment Owner for Cost:'
        default: 'Release Engineering'
        required: true


jobs:
  TerraformCD:
    strategy:
      matrix:
        application: ${{ fromJson(inputs.application) }}
    uses: easyjet-dev/reusable-workflows/.github/workflows/terraform-cd-using-oidc.yml@main
    with:
      environment: ${{ inputs.aws_account_name }}
      tf_version: '0.15'
      tf_workspace: ${{ inputs.aws_account_name }}
      destroy_enabled : ${{ inputs.destroy_enabled }}
      tfstate_key: "${{ inputs.envtype }}/${{ inputs.aws_account_name }}/${{ matrix.application }}.tfstate"
      additional_tfvars: '-var ''aws_account_id=${{ inputs.aws_account_id }}'' -var ''env_type=${{ inputs.envtype }}'' -var ''app_type=${{ matrix.application }}'' -var ''project=${{ inputs.project }}'' -var ''CostOwnerTeam=${{ inputs.costowner }}'' -var ''ext_lb_enabled=${{ inputs.ext_lb_enabled }}'' -var-file ''environment_input_files/${{ matrix.application }}.auto.tfvars.json'''
    secrets: inherit
